### ISSUE TITLE
Cherry-pick debuginfo non-determinism fix

### ISSUE THREAD

**Issue by glandium** [tstellar/llvm-project#757]
93a20ecee4b6c6618e0a8e1112f4f929d55ffcbb fixes a debuginfo determinism regression from 323049329939becf690adbeeff9f5f7e219075ec.

Cc: @tstellar

**Comment by tstellar** [comment]
I filed a bug on the official tracker for this: https://github.com/llvm/llvm-project/issues/52814

**Comment by tstellar** [comment]
/pull-request https://github.com/tstellar/llvm-project/pull/758
